### ISSUE TITLE
written in nodejs

### ISSUE THREAD

**Issue by buziyborni** [mgranderath/SPaaS#44]
i like this project but i don't no goland how to i write this project in nodejs?

**Comment by mgranderath** [comment]
Hey! Thank you for your interest! I've actually had a similar project in nodejs that I would count as a predecessor 😄You should be able to take extend that if you want to! https://github.com/mgranderath/PiaaS-legacy

**Comment by buziyborni** [comment]
Thanks sir I will take a look at it
